// End-to-end coverage for the MCP gateway.
//
// Everything else in this directory inspects tool definitions in-process.
// That is how `re.read_state` shipped pointing at `/api/state` — a Perception
// Engine path that no Reality Engine serves — and stayed broken across every
// runtime while the unit test asserted the wrong path was correct.
//
// These tests drive the real thing instead: the gateway runs as its own
// process, speaks Streamable HTTP, and talks to a stub engine whose route
// table is extracted from the C++ runtime (test/fixtures/engine-routes.json,
// regenerated by `npm run routes:gen`). Because the routes come from the
// engine rather than from the tools under test, a tool aimed at a path
// nothing serves has nowhere to land and the call fails.

import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { once } from 'node:events';

import { TOOLS } from '../src/tools.js';

const here = dirname(fileURLToPath(import.meta.url));
const gatewayEntry = resolve(here, '../src/http-server.js');
const routes = JSON.parse(readFileSync(resolve(here, 'fixtures/engine-routes.json'), 'utf8'));

// ── Stub engine ────────────────────────────────────────────────────────────

/** `GET /api/dispatch/records/:id` matches `GET /api/dispatch/records/abc`. */
function routeMatches(pattern, method, pathname) {
  const [patMethod, patPath] = pattern.split(' ');
  if (patMethod !== method) return false;
  const pat = patPath.split('/');
  const got = pathname.split('/');
  if (pat.length !== got.length) return false;
  return pat.every((seg, i) => (seg.startsWith(':') ? got[i].length > 0 : seg === got[i]));
}

/**
 * Serves exactly the routes the named engine serves and 404s everything else.
 * `failPaths` forces a 500 so error propagation can be exercised.
 */
function startStubEngine(target, { failPaths = new Set() } = {}) {
  const seen = [];
  const table = routes[target];
  const server = createServer((req, res) => {
    const { pathname } = new URL(req.url, 'http://stub');
    seen.push(`${req.method} ${pathname}`);

    if (failPaths.has(pathname)) {
      res.writeHead(500, { 'content-type': 'application/json' });
      return res.end(JSON.stringify({ error: 'stub failure' }));
    }
    if (!table.some((r) => routeMatches(r, req.method, pathname))) {
      res.writeHead(404, { 'content-type': 'application/json' });
      return res.end(JSON.stringify({ error: `no such route: ${req.method} ${pathname}` }));
    }
    // Drain any request body before replying.
    req.resume();
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ ok: true, target, path: pathname }));
  });
  return { server, seen };
}

function listen(server) {
  return new Promise((res) => server.listen(0, '127.0.0.1', () => res(server.address().port)));
}

// ── MCP client ─────────────────────────────────────────────────────────────

/** Streamable HTTP replies are SSE frames; pull the JSON out of `data:`. */
function parseSse(text) {
  for (const line of text.split('\n')) {
    if (line.startsWith('data:')) {
      try {
        return JSON.parse(line.slice(5).trim());
      } catch {
        /* keep scanning */
      }
    }
  }
  try {
    return JSON.parse(text);
  } catch {
    return { raw: text };
  }
}

class McpClient {
  constructor(baseUrl) {
    this.baseUrl = baseUrl;
    this.sessionId = '';
    this.nextId = 1;
  }

  async send(method, params) {
    const headers = {
      accept: 'application/json, text/event-stream',
      'content-type': 'application/json',
    };
    if (this.sessionId) headers['mcp-session-id'] = this.sessionId;
    const res = await fetch(`${this.baseUrl}/mcp`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ jsonrpc: '2.0', id: this.nextId++, method, params }),
    });
    const sid = res.headers.get('mcp-session-id');
    if (sid) this.sessionId = sid;
    return parseSse(await res.text());
  }

  async initialize() {
    const out = await this.send('initialize', {
      protocolVersion: '2024-11-05',
      capabilities: {},
      clientInfo: { name: 'mcp-e2e', version: '1.0.0' },
    });
    await this.send('notifications/initialized');
    return out;
  }

  call(name, args = {}) {
    return this.send('tools/call', { name, arguments: args });
  }
}

async function waitForHealth(baseUrl, timeoutMs = 15000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`${baseUrl}/healthz`);
      if (res.ok) return true;
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 100));
  }
  throw new Error(`MCP gateway did not become healthy at ${baseUrl}`);
}

/** Boot a gateway process wired to the stub engines. */
async function startGateway(env, reUrl, peUrl) {
  const probe = createServer();
  const port = await listen(probe);
  probe.close();
  await once(probe, 'close');

  const child = spawn(process.execPath, [gatewayEntry], {
    env: {
      ...process.env,
      RE_URL: reUrl,
      PE_URL: peUrl,
      RE_REGISTRY_URL: '',
      RE_MCP_HTTP_PORT: String(port),
      RE_MCP_HTTP_HOST: '127.0.0.1',
      RE_MCP_TIMEOUT_MS: '5000',
      ...env,
    },
    stdio: ['ignore', 'ignore', 'pipe'],
  });
  child.stderr.resume();

  const baseUrl = `http://127.0.0.1:${port}`;
  await waitForHealth(baseUrl);
  return { child, baseUrl };
}

// ── Fixtures ───────────────────────────────────────────────────────────────

let reStub;
let peStub;
let gateway;
let client;

/** Minimum arguments each tool needs to build a request. */
const TOOL_ARGS = {
  're.read_machine': { id: 'machine-probe' },
  'dispatch.read_record': { id: 'dispatch-probe' },
  'pe.push_signal': { sensorId: 'probe', values: [1] },
  'pe.sensor_push': { sensorId: 'probe', values: [1] },
  'trigger.replay': { dispatchId: 'dispatch-probe' },
  'dispatch.update_record': { id: 'dispatch-probe', status: 'delivered' },
  'integrations.completion': { sensorId: 'probe', values: [1], provider: 'probe' },
  'integrations.dispatch_provider': { provider: 'ollama', dispatchId: 'dispatch-probe' },
  'integrations.dispatch_openai': { dispatchId: 'dispatch-probe' },
  'integrations.dispatch_ollama': { dispatchId: 'dispatch-probe' },
  're.perceive': { vector: [0, 1] },
};

const readTools = TOOLS.filter((t) => !t.mutating);
const writeTools = TOOLS.filter((t) => t.mutating);

before(async () => {
  reStub = startStubEngine('re');
  peStub = startStubEngine('pe');
  const rePort = await listen(reStub.server);
  const pePort = await listen(peStub.server);
  gateway = await startGateway({}, `http://127.0.0.1:${rePort}`, `http://127.0.0.1:${pePort}`);
  client = new McpClient(gateway.baseUrl);
  await client.initialize();
});

after(async () => {
  gateway?.child.kill('SIGKILL');
  reStub?.server.close();
  peStub?.server.close();
});

// ── Tests ──────────────────────────────────────────────────────────────────

test('the gateway serves the full tool catalogue over Streamable HTTP', async () => {
  const res = await client.send('tools/list');
  const names = (res.result?.tools ?? []).map((t) => t.name).sort();
  assert.deepEqual(names, TOOLS.map((t) => t.name).sort());
});

test('every read tool reaches a route its target engine actually serves', async () => {
  // The regression this suite exists for. A tool whose path no engine serves
  // gets a 404 from the stub and surfaces as isError.
  const broken = [];
  for (const tool of readTools) {
    const res = await client.call(tool.name, TOOL_ARGS[tool.name] ?? {});
    const text = res.result?.content?.map((c) => c.text).join('') ?? '';
    if (res.result?.isError || res.error) {
      broken.push(`${tool.name} -> ${res.error?.message ?? text}`.slice(0, 160));
    }
  }
  assert.deepEqual(broken, [], `tools failed against the stub engines:\n${broken.join('\n')}`);
});

test('no RE tool is aimed at a Perception-Engine-only path', async () => {
  // re.read_state pointed at /api/state, which only the PE serves. Comparing
  // the two route tables catches that statically, without a running engine.
  const rePaths = new Set(routes.re.map((r) => r.split(' ')[1]));
  const pePaths = new Set(routes.pe.map((r) => r.split(' ')[1]));

  const misdirected = [];
  for (const tool of TOOLS) {
    const { path } = tool.build(TOOL_ARGS[tool.name] ?? {});
    const table = tool.target === 're' ? rePaths : pePaths;
    const other = tool.target === 're' ? pePaths : rePaths;
    // Compare on the literal prefix so :id routes still line up.
    const known = [...table].some((p) => pathShapeMatches(p, path));
    const onlyOther = !known && [...other].some((p) => pathShapeMatches(p, path));
    if (onlyOther) {
      misdirected.push(`${tool.name} (target=${tool.target}) -> ${path} is served only by the other engine`);
    }
  }
  assert.deepEqual(misdirected, []);
});

test('every tool path exists in its target engine route table', async () => {
  const missing = [];
  for (const tool of TOOLS) {
    const built = tool.build(TOOL_ARGS[tool.name] ?? {});
    const table = routes[tool.target];
    if (!table.some((r) => routeMatches(r, built.method, built.path))) {
      missing.push(`${tool.name} -> ${built.method} ${built.path}`);
    }
  }
  assert.deepEqual(missing, [], `tool paths absent from the engine route tables:\n${missing.join('\n')}`);
});

test('mutating tools are refused unless explicitly enabled', async () => {
  const allowed = [];
  for (const tool of writeTools) {
    const res = await client.call(tool.name, TOOL_ARGS[tool.name] ?? {});
    const text = res.result?.content?.map((c) => c.text).join('') ?? '';
    const refused = Boolean(res.result?.isError) || /disabled|not allowed|mutation/i.test(text);
    if (!refused) allowed.push(tool.name);
  }
  assert.deepEqual(allowed, [], 'mutating tools ran without an opt-in');
});

test('an allowlist enables exactly the named mutating tool', async () => {
  const gw = await startGateway(
    { RE_MCP_ALLOWED_TOOLS: 'pe.enqueue_push' },
    `http://127.0.0.1:${reStub.server.address().port}`,
    `http://127.0.0.1:${peStub.server.address().port}`
  );
  try {
    const c = new McpClient(gw.baseUrl);
    await c.initialize();

    const allowedCall = await c.call('pe.enqueue_push', {});
    assert.equal(allowedCall.result?.isError, undefined, 'allowlisted tool should run');

    const blocked = await c.call('pe.sensor_push', TOOL_ARGS['pe.sensor_push']);
    const text = blocked.result?.content?.map((x) => x.text).join('') ?? '';
    assert.ok(
      blocked.result?.isError || /disabled|not allowed|mutation/i.test(text),
      'a tool outside the allowlist should stay refused'
    );
  } finally {
    gw.child.kill('SIGKILL');
  }
});

test('an engine failure surfaces as a tool error rather than a hang', async () => {
  const failing = startStubEngine('re', { failPaths: new Set(['/api/machines']) });
  const port = await listen(failing.server);
  const gw = await startGateway(
    {},
    `http://127.0.0.1:${port}`,
    `http://127.0.0.1:${peStub.server.address().port}`
  );
  try {
    const c = new McpClient(gw.baseUrl);
    await c.initialize();
    const res = await c.call('re.list_machines', {});
    const text = res.result?.content?.map((x) => x.text).join('') ?? '';
    assert.ok(res.result?.isError || /500|stub failure/.test(text), 'engine 500 should propagate');
  } finally {
    gw.child.kill('SIGKILL');
    failing.server.close();
  }
});

test('an unknown instance selector is reported, not silently defaulted', async () => {
  const res = await client.call('re.list_machines', { instance: 'no-such-runtime' });
  const text = res.result?.content?.map((x) => x.text).join('') ?? '';
  assert.ok(
    res.result?.isError || /unknown instance/i.test(text),
    'selecting a missing instance should be an error'
  );
});

/** Structural comparison that tolerates `:id` segments on either side. */
function pathShapeMatches(pattern, path) {
  const pat = pattern.split('/');
  const got = path.split('/');
  if (pat.length !== got.length) return false;
  return pat.every((seg, i) => seg.startsWith(':') || seg === got[i]);
}
