#!/usr/bin/env python3
"""Bring the full corpus up one domain at a time, recording each domain's CES
contract shard as it lands.

**The shape.** Start from whatever corpus the universe booted on, then for each
domain in turn: generate the deployment artifacts the domain needs, import its
machines into all three runtimes, prove all three actually took them, and record
that domain's contract shard. The corpus grows cumulatively, so by the last
domain every engine holds the full corpus and every domain has a shard.

**Why incremental rather than a full-corpus boot.** A boot loads 1328 machines
and tells you one number at the end. If a runtime silently skipped a file you
learn that the totals differ, not which domain, and not which machine — and the
corpus read is the one operation where nothing raises: a machine that fails to
parse is a machine that is simply not there afterwards. Loading a domain at a
time makes the load count checkable against a known delta at each step, so a
miss is attributed to the domain that caused it, at the moment it happens.

**Load-count parity is the gate, and it is 3-of-3.** After each domain every
runtime must report exactly `before + len(domain)`. Equality between runtimes is
not sufficient on its own — three runtimes that all skipped the same malformed
file agree perfectly — so the expected absolute count is checked too.

**Failures are marked, and the sweep moves on.** A domain that fails to load or
to record is journalled and the next domain is attempted, because eleven domains
recorded and one marked is a better outcome than a sweep that stopped at the
first problem. The exception is a lost quorum, which is one universe-level fault
and halts rather than being reported once per remaining domain.

Usage:
  scripts/bring-up-corpus-incrementally.py --run
  scripts/bring-up-corpus-incrementally.py --plan            # print and exit
  scripts/bring-up-corpus-incrementally.py --run --only energy,agriculture
  scripts/bring-up-corpus-incrementally.py --run --skip-failed
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path
from typing import Any
from urllib import error, request

# Line-buffer stdout. Python block-buffers when stdout is a file rather than a
# tty, so a redirected sweep writes NOTHING until the buffer fills or the process
# exits. Measured: 40 minutes into a run, `final-sweep.log` was 0 bytes while two
# domains had already been recorded — the run was healthy and completely
# unobservable, and a log tail watching it saw silence indistinguishable from a
# hang. A long run that cannot be watched is one nobody can tell is progressing.
sys.stdout.reconfigure(line_buffering=True)

CI_DIR = Path(__file__).resolve().parent.parent
WS = CI_DIR.parent
MACHINES_REPO = WS / "RealityEngine_Machines"
DOMAINS_DIR = MACHINES_REPO / "machines" / "domains"
REGISTRY_JSON = MACHINES_REPO / "domains" / "ces-contract-registry.json"
BUILDER = MACHINES_REPO / "scripts" / "build-ces-contract-registry.py"
SHARD_DRIVER = CI_DIR / "scripts" / "record-ces-contract-shards.sh"
INSTANCE_REGISTRY = Path("/tmp/re-registry/re-registry.json")
JOURNAL = CI_DIR / ".ces-contracts" / "bring-up-journal.json"

NATIVE_QUORUM = ("cpp", "lsp", "scala")

# The deployment artifacts a domain load needs present. They live under a
# gitignored directory: generated by the lane that needs them, never tracked.
# Regenerated before every domain because each one changes the corpus they are
# projected from — a lane graph built before a domain arrived does not describe
# the corpus the engines are now holding.
DEPLOYMENT_ARTIFACTS = [
    ("project-lanes.py", "semantics/lanes/lane-graph.ttl"),
    ("compile-decision-table.py", "semantics/lanes/decision-table.json"),
]


# ── HTTP ────────────────────────────────────────────────────────────────────

def http(method: str, url: str, body: str | None = None, timeout: int = 60) -> tuple[int, Any]:
    req = request.Request(
        url, method=method,
        data=body.encode("utf-8") if body is not None else None,
        headers={"content-type": "application/json", "accept": "application/json"})
    try:
        with request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read().decode("utf-8", "replace")
            try:
                return resp.status, json.loads(raw) if raw else None
            except json.JSONDecodeError:
                return resp.status, {"raw": raw[:400]}
    except error.HTTPError as exc:
        raw = exc.read().decode("utf-8", "replace")
        return exc.code, {"raw": raw[:400]}
    except Exception as exc:  # noqa: BLE001
        return 0, {"raw": repr(exc)}


# ── Universe ────────────────────────────────────────────────────────────────

def instances() -> list[dict[str, str]]:
    try:
        data = json.loads(INSTANCE_REGISTRY.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        raise SystemExit(f"could not read {INSTANCE_REGISTRY}: {exc}") from exc
    out = [{"id": i.get("id", i["runtime"]), "runtime": i["runtime"],
            "re_url": (i.get("re_url") or "").rstrip("/"),
            "pe_url": (i.get("pe_url") or "").rstrip("/")}
           for i in data.get("instances", [])
           if i.get("status", "running") == "running" and i.get("runtime") in NATIVE_QUORUM]
    return sorted(out, key=lambda i: i["id"])


def quorum_formed(insts: list[dict[str, str]]) -> tuple[bool, list[str]]:
    present = {i["runtime"] for i in insts}
    missing = [r for r in NATIVE_QUORUM if r not in present]
    return not missing, missing


def registry_machines(inst: dict[str, str]) -> list[dict[str, Any]] | None:
    """The runtime's IN-MEMORY machine registry.

    `GET /api/machines`, not `GET /api/machines/json/list`. They answer different
    questions and the difference is invisible until you import something:
    `json/list` is a catalog of the corpus files ON DISK, so a machine imported
    into a running engine never appears in it, while the in-memory registry is
    what the engine will actually evaluate.

    Measured here during the first trial: after importing nine machines into cpp
    and lsp, `json/list` still said 21 on all three — perfect agreement, and
    perfectly wrong. The load had succeeded on two runtimes and failed on the
    third, and the endpoint that looked like a load count could not see any of it.
    """
    status, payload = http("GET", f"{inst['re_url']}/api/machines")
    if not 200 <= status < 300:
        return None
    machines = payload.get("machines", payload) if isinstance(payload, dict) else payload
    return machines if isinstance(machines, list) else None


def machine_count(inst: dict[str, str]) -> int | None:
    machines = registry_machines(inst)
    return None if machines is None else len(machines)


# ── Deployment artifacts ────────────────────────────────────────────────────

def regenerate_deployment_artifacts() -> list[str]:
    """The before-action on loading a domain.

    These are deployment artifacts, not source: `semantics/lanes/` is gitignored
    and the lane that needs them generates them. Written unconditionally here —
    unlike the validation gate, which regenerates only what is absent so a stale
    artifact still fails a check. This is not a check; it is the step that makes
    the artifacts describe the corpus about to be loaded.
    """
    problems = []
    for script, output in DEPLOYMENT_ARTIFACTS:
        result = subprocess.run(
            [sys.executable, str(MACHINES_REPO / "scripts" / script), "--write"],
            capture_output=True, text=True, cwd=MACHINES_REPO)
        if result.returncode != 0:
            problems.append(f"{script}: {(result.stderr or result.stdout).strip()[:200]}")
        elif not (MACHINES_REPO / output).exists():
            problems.append(f"{script}: reported success but {output} is absent")
    return problems


# ── Loading one domain ──────────────────────────────────────────────────────

def domain_files(domain: str) -> list[Path]:
    return sorted((DOMAINS_DIR / domain).rglob("*.json"))


def machine_name(path: Path) -> str | None:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    machine = raw.get("machine", raw) if isinstance(raw, dict) else {}
    return machine.get("name")


def resident_names(inst: dict[str, str]) -> set[str]:
    """What this runtime holds, keyed by machine NAME.

    Name rather than id: every runtime mints its own id for the same logical
    machine, so ids are not comparable across the quorum — the same reason the
    parity census keys on name. Name is declared by the corpus file and survives
    the round trip unchanged.
    """
    machines = registry_machines(inst) or []
    return {m.get("name") for m in machines if isinstance(m, dict) and m.get("name")}


def load_domain(domain: str, insts: list[dict[str, str]]) -> dict[str, Any]:
    """Import a domain's machines into every runtime and prove all three took them.

    Returns a report. Per-machine failures are collected and named rather than
    counted: "3 machines failed on lsp" sends the reader to the logs to find out
    which, and the whole reason for loading a domain at a time is to not have to.
    """
    files = domain_files(domain)
    before = {i["id"]: machine_count(i) for i in insts}
    if any(c is None for c in before.values()):
        unreadable = sorted(k for k, v in before.items() if v is None)
        return {"ok": False, "stage": "pre-count",
                "error": f"could not read machine count from {', '.join(unreadable)}"}

    already = {i["id"]: resident_names(i) for i in insts}
    failures: dict[str, list[str]] = {i["id"]: [] for i in insts}
    imported: dict[str, int] = {i["id"]: 0 for i in insts}

    for path in files:
        body = path.read_text(encoding="utf-8")
        name = machine_name(path)
        for inst in insts:
            if name and name in already[inst["id"]]:
                continue  # already held; importing again would double-register
            # POST /api/machines, not /api/machines/json/import. The latter is
            # unreachable on Scala: `path("json" / Segment)` is declared before
            # `path("json" / "import")` in Routes.scala and shadows it, so the
            # import arrives at a handler that cannot decode it and answers 400.
            # cpp and lsp both serve it. Using the endpoint all three actually
            # implement keeps one payload shape for the whole quorum rather than
            # special-casing one runtime, which would hide the divergence
            # instead of routing around it. The shadowing itself is a Scala
            # defect and is reported separately.
            status, payload = http("POST", f"{inst['re_url']}/api/machines", body)
            if 200 <= status < 300:
                imported[inst["id"]] += 1
            else:
                detail = (payload or {}).get("raw", "") if isinstance(payload, dict) else ""
                failures[inst["id"]].append(f"{path.name}: HTTP {status} {detail[:120]}")

    after = {i["id"]: machine_count(i) for i in insts}
    expected = {i["id"]: before[i["id"]] + imported[i["id"]] for i in insts}

    # Two distinct checks. Equality across runtimes alone would pass three
    # runtimes that all skipped the same file; the absolute expectation is what
    # catches a load that silently did less than it was asked to.
    counts_agree = len(set(after.values())) == 1
    counts_expected = all(after[k] == expected[k] for k in after)
    any_failures = any(failures.values())

    return {
        "ok": counts_agree and counts_expected and not any_failures,
        "stage": "load",
        "files": len(files),
        "before": before, "after": after, "expected": expected,
        "imported": imported,
        "countsAgree": counts_agree,
        "countsMatchExpected": counts_expected,
        "failures": {k: v for k, v in failures.items() if v},
    }


# ── Unloading one domain ────────────────────────────────────────────────────

def boot_corpus_names() -> set[str]:
    """The machines the universe booted with — the floor an unload restores to.

    Read from the corpus list the universe was started on, not from a snapshot
    taken at some arbitrary moment, because a snapshot taken after a domain was
    already loaded would enshrine that domain as part of the floor and it would
    never be removed again.

    Boot machines are themselves domain machines — the regression corpus draws
    DLX011 from digital-logic, FallDetection from health-personal — so "unload
    the domain" cannot mean "delete every file in the domain directory". It
    means delete what we added, which is the domain minus the floor.
    """
    names: set[str] = set()
    listing = CI_DIR / "config" / "regression-corpus.txt"
    roots = [MACHINES_REPO / "machines", WS / "localAIStack" / "data" / "machines"]
    if not listing.exists():
        return names
    for line in listing.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        base = line.split("/")[-1]
        for root in roots:
            hit = next(iter(root.rglob(base)), None)
            if hit:
                name = machine_name(hit)
                if name:
                    names.add(name)
                break
    return names


def removable_names(domain: str, floor: set[str]) -> set[str]:
    own = {machine_name(f) for f in domain_files(domain)}
    return {n for n in own if n and n not in floor}


def unload_domain(domain: str, insts: list[dict[str, Any]], floor: set[str]) -> dict[str, Any]:
    """Delete this domain's machines from every runtime and prove all three did.

    Deleted by NAME resolved to each runtime's own id. Imported machines are
    given runtime-minted ids — measured: `machine-1789255613939-420023239` on
    cpp, `machine-1U4G94T-QS62LSJ9WRV9` on lsp, `machine-1789255613943-dda3166d`
    on scala for the same logical machine — so there is no shared id to delete
    by and a single id list would silently miss on two runtimes out of three.

    The post-condition is checked as hard as the load's. A partial unload does
    not announce itself: it inflates the next domain's resident count, which
    slows it, and leaves foreign machines resident while that domain is
    recorded — the exact contamination isolation exists to remove.
    """
    want = removable_names(domain, floor)
    before = {i["id"]: machine_count(i) for i in insts}
    failures: dict[str, list[str]] = {i["id"]: [] for i in insts}
    removed: dict[str, int] = {i["id"]: 0 for i in insts}

    for inst in insts:
        for m in registry_machines(inst) or []:
            if not isinstance(m, dict) or m.get("name") not in want:
                continue
            status, _ = http("DELETE", f"{inst['re_url']}/api/machines/{m['id']}")
            if 200 <= status < 300:
                removed[inst["id"]] += 1
            else:
                failures[inst["id"]].append(f"{m.get('name')}: HTTP {status}")

    after = {i["id"]: machine_count(i) for i in insts}
    still = {i["id"]: sorted(want & resident_names(i)) for i in insts}
    lingering = {k: v for k, v in still.items() if v}
    return {
        "ok": not any(failures.values()) and not lingering
              and len(set(after.values())) == 1,
        "before": before, "after": after, "removed": removed,
        "failures": {k: v for k, v in failures.items() if v},
        "lingering": lingering,
    }


def restore_to_floor(insts: list[dict[str, Any]], floor: set[str]) -> dict[str, Any]:
    """Remove every domain machine above the floor, whatever put it there.

    Run once before an isolated sweep. The universe may already be carrying
    domains from an earlier cumulative run — and a domain recorded on top of
    those is not isolated, it just looks like it.
    """
    all_domain_names: set[str] = set()
    for d in sorted(DOMAINS_DIR.iterdir()):
        if d.is_dir():
            all_domain_names |= {machine_name(f) for f in domain_files(d.name)}
    surplus = {n for n in all_domain_names if n} - floor

    removed = {i["id"]: 0 for i in insts}
    for inst in insts:
        for m in registry_machines(inst) or []:
            if isinstance(m, dict) and m.get("name") in surplus:
                status, _ = http("DELETE", f"{inst['re_url']}/api/machines/{m['id']}")
                if 200 <= status < 300:
                    removed[inst["id"]] += 1
    after = {i["id"]: machine_count(i) for i in insts}
    return {"removed": removed, "after": after, "agree": len(set(after.values())) == 1}


# ── Recording one domain ────────────────────────────────────────────────────

def record_domain(domain: str) -> dict[str, Any]:
    """Record this domain's shard from the corpus's own composed seed.

    Calls scripts/record-ces-contracts.py directly rather than going through
    record-ces-contract-shards.sh. The shell driver selects *scopes* for the
    retired per-chain recorder, which drove one chain at a time through a source
    it registered itself — a synthetic stimulus (SURFACE_SPEC.md). The recorder
    now arms the interned sources and drives the whole resident corpus once, so
    there is no per-chain scope to select; the domain is a projection of that
    run, chosen with --only.

    --only matters under isolation. The floor corpus the universe boots on holds
    machines from several domains, so an unfiltered write would emit a shard for
    each of those covering only the few resident, overwriting a complete shard
    with a partial one that looks just as authoritative.
    """
    result = subprocess.run(
        ["python3", str(CI_DIR / "scripts" / "record-ces-contracts.py"),
         "--only", domain, "--write"],
        capture_output=True, text=True, cwd=CI_DIR)
    summary = ""
    for line in (result.stdout or "").splitlines():
        if line.strip().startswith(domain + " ") or f"  {domain:22}" in line:
            summary = " ".join(line.split())
    return {"ok": result.returncode == 0, "summary": summary,
            "output": (result.stdout or "")[-2000:], "error": (result.stderr or "")[-1000:]}


# ── Journal ─────────────────────────────────────────────────────────────────

def read_journal() -> dict[str, Any]:
    try:
        return json.loads(JOURNAL.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return {"version": "1.0.0", "domains": {}}


def write_journal(doc: dict[str, Any]) -> None:
    JOURNAL.parent.mkdir(parents=True, exist_ok=True)
    tmp = JOURNAL.with_suffix(".tmp")
    tmp.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(JOURNAL)


def mark(domain: str, outcome: str, detail: dict[str, Any]) -> None:
    doc = read_journal()
    entry = doc["domains"].get(domain, {})
    entry["attempts"] = entry.get("attempts", 0) + 1
    entry["outcome"] = outcome
    entry["lastAttemptAt"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    entry["detail"] = detail
    doc["domains"][domain] = entry
    doc["updatedAt"] = entry["lastAttemptAt"]
    write_journal(doc)


# ── Plan ────────────────────────────────────────────────────────────────────

def plan(only: str | None, skip_failed: bool) -> list[tuple[str, int, int]]:
    registry = json.loads(REGISTRY_JSON.read_text(encoding="utf-8"))
    journal = read_journal()["domains"]
    wanted = {d.strip() for d in only.split(",") if d.strip()} if only else None
    rows = []
    for scope, entry in registry["scopes"].items():
        if entry["kind"] != "domain":
            continue
        name = entry["name"]
        if wanted is not None and name not in wanted:
            continue
        if entry["status"] == "recorded":
            continue
        if skip_failed and journal.get(name, {}).get("outcome", "").startswith("failed"):
            continue
        rows.append((name, entry["machineCount"], entry["chainCount"]))
    return sorted(rows, key=lambda r: r[2])


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--run", action="store_true")
    mode.add_argument("--plan", action="store_true")
    p.add_argument("--only", help="Comma-separated domain names.")
    p.add_argument("--skip-failed", action="store_true",
                   help="Step past domains the journal already records as failed.")
    p.add_argument("--max-consecutive", type=int, default=3,
                   help="Halt after N failures in a row (0 disables).")
    # Isolation is the default because it is both faster and stricter. Cost is
    # chains x resident, and under cumulative loading both factors grow together
    # — measured, the last domain costs 201 minutes against 29 for the same work
    # isolated, and the final three domains are 69% of a 12-hour sweep. Holding
    # resident flat makes the whole sweep 2.6h. It is also the stronger
    # guarantee: cumulative recording relies on sequence-id filtering to screen
    # out every other resident domain, while isolation leaves nothing to screen.
    p.add_argument("--isolate", dest="isolate", action="store_true", default=True,
                   help="load -> record -> unload each domain (default).")
    p.add_argument("--cumulative", dest="isolate", action="store_false",
                   help="Leave each domain loaded. Slower, and purity then rests "
                        "on sequence-id filtering rather than on absence.")
    p.add_argument("--final-load", action="store_true",
                   help="After the sweep, import the whole corpus so the engines "
                        "end up holding it. ~1 minute; records nothing.")
    args = p.parse_args()

    subprocess.run([sys.executable, str(BUILDER), "--write"],
                   capture_output=True, text=True, cwd=MACHINES_REPO)
    rows = plan(args.only, args.skip_failed)
    if not rows:
        print("nothing to do — every selected domain is recorded or filtered out")
        return 0

    print(f"{len(rows)} domain(s), cheapest first:")
    for name, machines, chains in rows:
        print(f"  {name:<22} {machines:>5} machines  {chains:>6} chains")
    total = sum(r[2] for r in rows)
    print(f"  {'':22} {sum(r[1] for r in rows):>5} machines  {total:>6} chains total")
    if args.plan:
        return 0

    insts = instances()
    formed, missing = quorum_formed(insts)
    if not formed:
        print(f"quorum not formed: missing {'+'.join(missing)}", file=sys.stderr)
        return 2

    floor: set[str] = set()
    if args.isolate:
        floor = boot_corpus_names()
        if not floor:
            print("could not resolve the boot corpus — refusing to unload against "
                  "an unknown floor", file=sys.stderr)
            return 2
        print(f"\nfloor: {len(floor)} machines the universe booted with; "
              f"domains are unloaded back to this after each recording")
        restored = restore_to_floor(insts, floor)
        if any(restored["removed"].values()):
            print(f"  cleared {restored['removed']} left over from an earlier run "
                  f"-> {restored['after']}")
        if not restored["agree"]:
            print(f"  runtimes disagree after restore: {restored['after']}", file=sys.stderr)
            return 2

    done = failed = 0
    consecutive = 0
    for name, machines, chains in rows:
        insts = instances()
        formed, missing = quorum_formed(insts)
        if not formed:
            # One universe-level fault, not one per remaining domain.
            print(f"\nHALT: quorum lost — {'+'.join(missing)} not answering.")
            print("  remaining domains left unattempted rather than marked failed")
            break

        print(f"\n=== {name} ({machines} machines, {chains} chains) ===")

        problems = regenerate_deployment_artifacts()
        if problems:
            print("  deployment artifacts FAILED:")
            for line in problems:
                print(f"    {line}")
            mark(name, "failed-artifacts", {"problems": problems})
            failed += 1; consecutive += 1
        else:
            print("  deployment artifacts regenerated")
            report = load_domain(name, insts)
            if not report["ok"]:
                print(f"  load FAILED at {report['stage']}")
                if report.get("failures"):
                    for inst_id, errs in report["failures"].items():
                        print(f"    {inst_id}: {len(errs)} machine(s) rejected")
                        for e in errs[:5]:
                            print(f"      {e}")
                if not report.get("countsAgree", True):
                    print(f"    load-count parity: {report['after']}")
                if not report.get("countsMatchExpected", True):
                    print(f"    expected {report['expected']}, got {report['after']}")
                mark(name, "failed-load", report)
                failed += 1; consecutive += 1
            else:
                counts = ", ".join(f"{k}={v}" for k, v in sorted(report["after"].items()))
                print(f"  loaded — 3-of-3 parity at {counts}")
                rec = record_domain(name)
                if rec["ok"]:
                    print(f"  recorded — {rec['summary']}")
                    outcome, detail = "recorded", {"load": report, "summary": rec["summary"]}
                    if args.isolate:
                        un = unload_domain(name, insts, floor)
                        if un["ok"]:
                            print(f"  unloaded — back to {sorted(un['after'].values())[0]} "
                                  f"on all three")
                        else:
                            # The shard is already written and valid — it was
                            # recorded before this. What is compromised is every
                            # LATER domain, which would be recorded on top of
                            # residue. Recorded as its own outcome so the two are
                            # not confused.
                            print("  unload INCOMPLETE — later domains would not be isolated")
                            for k, v in (un["lingering"] or {}).items():
                                print(f"    {k}: {len(v)} machine(s) still resident")
                            for k, v in (un["failures"] or {}).items():
                                print(f"    {k}: {len(v)} delete(s) failed")
                            outcome = "recorded-unload-incomplete"
                            detail["unload"] = un
                    mark(name, outcome, detail)
                    done += 1; consecutive = 0
                    if outcome != "recorded":
                        print("  HALT: refusing to record further domains against residue")
                        break
                else:
                    print("  record FAILED")
                    for line in rec["output"].splitlines()[-6:]:
                        print(f"    {line}")
                    mark(name, "failed-record",
                         {"load": report, "output": rec["output"][-800:]})
                    failed += 1; consecutive += 1

        if args.max_consecutive > 0 and consecutive >= args.max_consecutive:
            print(f"\nHALT: {consecutive} consecutive failures — one systemic fault, "
                  f"not {consecutive} independent ones")
            break

    if args.final_load and not failed:
        print("\n=== final full-corpus load (no recording) ===")
        insts = instances()
        for d in sorted(p.name for p in DOMAINS_DIR.iterdir() if p.is_dir()):
            rep = load_domain(d, insts)
            flag = "ok" if rep["ok"] else "PROBLEM"
            print(f"  {d:<22}{flag}  {sorted(rep.get('after', {}).values())}")

    print(f"\nrecorded={done} failed={failed}   journal: {JOURNAL}")
    subprocess.run([sys.executable, str(BUILDER), "--write"],
                   capture_output=True, text=True, cwd=MACHINES_REPO)
    subprocess.run([sys.executable, str(BUILDER), "--status"], cwd=MACHINES_REPO)
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
