#!/usr/bin/env node
/**
 * ces-query — observability DSL over CES activation traces.
 *
 * Step 11 in the CES-roadmap: every vector has a stable id, every
 * mergeBatch entry carries (machine, sequence, provenance, governance,
 * deprecation, region, values).  That structured payload is a query
 * surface — a small DSL lets operators ask questions like
 *
 *   "Where machine='Fall Detection' AND lastVector='fall-conf-v4'
 *    GROUP BY hourOfDay"
 *
 * without writing custom logging code in the runtime.  This CLI runs
 * such queries against examples/contracts.json — the canonical replay of
 * 5,589 simulation steps generated by scripts/cesgen-contracts.mjs.  In
 * production the same DSL would back a panel against streamed engine
 * traces.
 *
 * Usage:
 *   node scripts/ces-query.mjs --list                 # show all canned queries
 *   node scripts/ces-query.mjs --query Q1             # run by id
 *   node scripts/ces-query.mjs --query Q1 --json      # JSON output
 *   node scripts/ces-query.mjs --all                  # run every query
 *   node scripts/ces-query.mjs --trace PATH           # alternate trace file
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');

// ── Synthetic time stamping ──────────────────────────────────────────────────

/**
 * The contracts file captures structural outputs but not when in wall-clock
 * time they happened.  For the demo we fabricate per-event timestamps by
 * hashing (contractId + stepIndex) into a 24-hour band.  Deterministic,
 * spread across the day, just enough for hour-of-day groupings to look
 * realistic.  A production deployment would use the engine's own
 * timestamps from /api/perceive or a streaming pipeline.
 */
function fnv1a(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = (h * 0x01000193) >>> 0;
  }
  return h;
}
function syntheticHourAndMinute(contractId, stepIdx, occurrence) {
  const h = fnv1a(`${contractId}:${stepIdx}:${occurrence}`);
  return {
    hourOfDay: h % 24,
    minute:    Math.floor(h / 24) % 60,
  };
}
/**
 * Per-contract replay count.  The contracts file pins ONE canonical
 * occurrence per chain, but a real activity log carries each chain
 * multiple times across a day.  We amplify deterministically so the
 * hour-of-day rollups show meaningful distributions without bloating
 * the trace file.  Range: 5..30 occurrences per chain.
 */
function replayCount(contractId) {
  return (fnv1a(`replay:${contractId}`) % 26) + 5;
}

// ── Trace flattener ──────────────────────────────────────────────────────────

/**
 * Flatten the contract file into one row per mergeBatch entry — the
 * shape the DSL queries operate on.  Joins the contract id (so callers
 * can group by chain), the synthetic timestamp, and the engine fields.
 *
 * Note: governance / deprecation are absent because cesgen-contracts
 * deliberately projects them out (see scripts/cesgen-contracts.mjs);
 * production traces would carry the full block.  We backfill governance
 * synthetically by looking up the machine JSON's triggerConfig.rules
 * so the governance-flavored queries can demonstrate value.
 */
function flattenContracts(file, machinesDir) {
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));

  // Build a per-machine sequence→rule lookup so we can backfill (rag,
  // status, ownerTeam) onto each row without re-running the engine.
  const ruleByMachine = new Map();
  for (const c of data.contracts) {
    if (ruleByMachine.has(c.machineFile)) continue;
    try {
      const raw = JSON.parse(fs.readFileSync(path.join(machinesDir, c.machineFile), 'utf8'));
      const m = raw.machine ?? raw;
      const rules = m.metadata?.triggerConfig?.rules ?? [];
      const gov = m.metadata?.governance ?? null;
      ruleByMachine.set(c.machineFile, { machine: m, rules, governance: gov });
    } catch (e) { ruleByMachine.set(c.machineFile, { machine: null, rules: [], governance: null }); }
  }

  const rows = [];
  for (const c of data.contracts) {
    const meta = ruleByMachine.get(c.machineFile);
    const machineName = meta?.machine?.name ?? c.machineFile;
    const replays = replayCount(c.id);
    for (let occ = 0; occ < replays; occ++) {
      for (const step of c.outputStream) {
        const t = syntheticHourAndMinute(c.id, step.step, occ);
        for (const op of step.mergeBatch) {
          const rule = (meta?.rules ?? []).find(r =>
            r.sequenceId === op.sequenceId &&
            arraysEqual(r.outputMatches, op.values));
          const ragStatusCode = rule?.ragStatusCode ?? null;
          const processStatus = rule?.processStatus ?? null;
          const ownerTeam = (rule?.governance?.ownerTeam) ?? meta?.governance?.ownerTeam ?? 'unrouted';
          rows.push({
            contractId:      c.id,
            occurrence:      occ,
            machineFile:     c.machineFile,
            machineName,
            step:             step.step,
            sequenceId:       op.sequenceId,
            lastVector:       op.provenance?.length ? op.provenance[op.provenance.length - 1] : null,
            provenance:       op.provenance ?? [],
            provenanceDepth: (op.provenance ?? []).length,
            regionOffset:     op.region.offset,
            regionLength:     op.region.length,
            values:           op.values,
            ragStatusCode,
            processStatus,
            ownerTeam,
            hourOfDay:        t.hourOfDay,
            minute:           t.minute,
            timeOfDay:        `${String(t.hourOfDay).padStart(2,'0')}:${String(t.minute).padStart(2,'0')}`,
          });
        }
      }
    }
  }
  return { rows, ruleByMachine };
}

function arraysEqual(a, b) {
  if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

// ── Tiny query helpers ──────────────────────────────────────────────────────

function groupBy(rows, keyFn) {
  const out = new Map();
  for (const r of rows) {
    const k = keyFn(r);
    const list = out.get(k);
    if (list) list.push(r); else out.set(k, [r]);
  }
  return out;
}

function topK(map, k, valueFn = v => v.length) {
  return [...map.entries()]
    .map(([key, value]) => ({ key, value, n: valueFn(value) }))
    .sort((a, b) => b.n - a.n)
    .slice(0, k);
}

// ── The canned queries ──────────────────────────────────────────────────────

const QUERIES = [
  {
    id: 'Q1',
    label: 'mid-fall validation timing',
    operationalQuestion: 'When do residents reach the mid-fall validation step (fall-imprec-v3) — the canonical example from the brief?',
    // Note on lastVector vs provenance: the brief's example used
    // `lastVector='fall-conf-vN'`, but in the engine `lastVector` is the
    // emitter — only terminals appear there.  The mid-fall validation
    // step `fall-conf-v4` is an intermediate.  The DSL treats `provenance
    // contains` as the equivalent for intermediates — it asks "did the
    // chain ever pass through vN before terminating?" — which is what
    // the operational question really wants.  We anchor on the deepest
    // chain present in the replayed trace (fall-impact-recovered, 4
    // steps, terminal fall-imprec-v4) so mid-validation = fall-imprec-v3.
    dsl: "WHERE machine='Fall Detection' AND provenance CONTAINS 'fall-imprec-v3' GROUP BY hourOfDay COUNT *",
    run: (rows) => {
      const hits = rows.filter(r =>
        r.machineFile === 'FallDetection.json' &&
        Array.isArray(r.provenance) && r.provenance.includes('fall-imprec-v3'));
      const byHour = groupBy(hits, r => r.hourOfDay);
      const out = [];
      for (let h = 0; h < 24; h++) {
        const n = (byHour.get(h) ?? []).length;
        if (n > 0) out.push({ hour: h, count: n });
      }
      return out;
    },
  },
  {
    id: 'Q2',
    label: 'top-10 most-fired terminal vectors',
    operationalQuestion: 'Which assertions dominate engine output?',
    dsl: "GROUP BY (machine, sequence, lastVector) COUNT * ORDER BY count DESC LIMIT 10",
    run: (rows) => {
      const g = groupBy(rows, r => `${r.machineName}|${r.sequenceId}|${r.lastVector}`);
      return topK(g, 10).map(({ key, n }) => {
        const [machine, sequence, vector] = key.split('|');
        return { machine, sequence, vector, fires: n };
      });
    },
  },
  {
    id: 'Q3',
    label: 'time-of-day heatmap of RED fires by machine',
    operationalQuestion: 'What is the daily rhythm of life-safety paging?',
    dsl: "WHERE ragStatusCode='RED' GROUP BY (machine, hourOfDay) COUNT *",
    run: (rows) => {
      const reds = rows.filter(r => r.ragStatusCode === 'RED');
      const g = groupBy(reds, r => `${r.machineName}|${r.hourOfDay}`);
      const result = [...g.entries()].map(([k, list]) => {
        const [machine, hour] = k.split('|');
        return { machine, hourOfDay: Number(hour), reds: list.length };
      }).sort((a, b) => a.machine.localeCompare(b.machine) || a.hourOfDay - b.hourOfDay);
      return result.slice(0, 30);
    },
  },
  {
    id: 'Q4',
    label: 'provenance chain depth distribution',
    operationalQuestion: 'How much evidence does each machine accumulate before asserting?',
    dsl: "GROUP BY (machine, provenanceDepth) COUNT *",
    run: (rows) => {
      const g = groupBy(rows, r => `${r.machineName}|${r.provenanceDepth}`);
      const out = [...g.entries()].map(([k, list]) => {
        const [machine, depth] = k.split('|');
        return { machine, chainDepth: Number(depth), fires: list.length };
      }).sort((a, b) => a.machine.localeCompare(b.machine) || a.chainDepth - b.chainDepth);
      return out.slice(0, 40);
    },
  },
  {
    id: 'Q5',
    label: 'evidence-skip detection (provenance shorter than expected)',
    operationalQuestion: 'Is any fall-conf-v6 RED arriving with fewer than 6 evidence steps?  Drift / bug indicator.',
    dsl: "WHERE machine='Fall Detection' AND lastVector='fall-conf-v6' AND length(provenance) < 6",
    run: (rows) => rows
      .filter(r => r.machineFile === 'FallDetection.json' && r.lastVector === 'fall-conf-v6' && r.provenanceDepth < 6)
      .map(r => ({ contract: r.contractId, depth: r.provenanceDepth, provenance: r.provenance })),
  },
  {
    id: 'Q6',
    label: 'paging concentration by owner team',
    operationalQuestion: 'Which on-call team carries the most load?',
    dsl: "GROUP BY ownerTeam COUNT * ORDER BY count DESC",
    run: (rows) => {
      const g = groupBy(rows.filter(r => r.ownerTeam), r => r.ownerTeam);
      return topK(g, 15).map(({ key, n }) => ({ ownerTeam: key, totalDecisions: n }));
    },
  },
  {
    id: 'Q7',
    label: 'RED rate per machine',
    operationalQuestion: 'What fraction of each machine\'s outputs hit RED?  Identifies machines that page hot.',
    dsl: "GROUP BY machine SELECT machine, COUNT(rag='RED') / COUNT(*) AS redRate ORDER BY redRate DESC",
    run: (rows) => {
      const byMachine = groupBy(rows, r => r.machineName);
      const out = [];
      for (const [machine, list] of byMachine) {
        const total = list.length;
        if (total === 0) continue;
        const red = list.filter(r => r.ragStatusCode === 'RED').length;
        out.push({ machine, total, red, redRate: +(red / total).toFixed(3) });
      }
      return out.filter(r => r.red > 0).sort((a, b) => b.redRate - a.redRate).slice(0, 20);
    },
  },
  {
    id: 'Q8',
    label: 'untouched terminal vectors (long-tail coverage gap)',
    operationalQuestion: 'Which CES terminals are wired in the corpus but never fire in the replayed trace?',
    dsl: "(corpus terminals) MINUS (vectors observed in trace)",
    run: (rows, { ruleByMachine }) => {
      const observed = new Set(rows.filter(r => r.lastVector).map(r => `${r.machineFile}::${r.sequenceId}::${r.lastVector}`));
      const missing = [];
      for (const [file, meta] of ruleByMachine) {
        const m = meta?.machine;
        if (!m) continue;
        for (const seq of m.sequences ?? []) {
          for (const v of seq.vectors ?? []) {
            if (!(v.outputVectors?.length)) continue;
            const key = `${file}::${seq.id}::${v.id}`;
            if (!observed.has(key)) missing.push({ machineFile: file, sequence: seq.id, terminal: v.id });
          }
        }
      }
      // Show only first 12 — the full list is the operational backlog.
      return { totalMissing: missing.length, sample: missing.slice(0, 12) };
    },
  },
  {
    id: 'Q9',
    label: 'cross-machine event bus impact',
    operationalQuestion: 'Which producer (machine, sequence) pairs would feed a meta-CES?  Useful when wiring step-5 subscriptions.',
    dsl: "GROUP BY (machine, sequence) WHERE rag IN ('RED','AMBER') COUNT *",
    run: (rows) => {
      const escalations = rows.filter(r => r.ragStatusCode === 'RED' || r.ragStatusCode === 'AMBER');
      const g = groupBy(escalations, r => `${r.machineName}|${r.sequenceId}`);
      return topK(g, 15).map(({ key, n }) => {
        const [machine, sequence] = key.split('|');
        return { machine, sequence, escalations: n };
      });
    },
  },
  {
    id: 'Q10',
    label: 'multi-stage progression coverage',
    operationalQuestion: 'For each chained sequence, what fraction of intermediate vectors ever fire?',
    dsl: "GROUP BY (machine, sequence) SELECT firedVectors / declaredVectors",
    run: (rows, { ruleByMachine }) => {
      const firedByMS = new Map();
      for (const r of rows) {
        if (!r.lastVector) continue;
        const key = `${r.machineFile}::${r.sequenceId}`;
        const set = firedByMS.get(key) ?? new Set();
        for (const v of r.provenance ?? []) set.add(v);
        firedByMS.set(key, set);
      }
      const out = [];
      for (const [file, meta] of ruleByMachine) {
        const m = meta?.machine;
        if (!m) continue;
        for (const seq of m.sequences ?? []) {
          const declared = (seq.vectors ?? []).length;
          if (declared <= 1) continue;
          const fired = (firedByMS.get(`${file}::${seq.id}`) ?? new Set()).size;
          out.push({ machine: m.name, sequence: seq.id, declared, fired, coverage: +(fired / declared).toFixed(2) });
        }
      }
      return out.sort((a, b) => a.coverage - b.coverage).slice(0, 15);
    },
  },
  {
    id: 'Q11',
    label: 'co-firing pairs within the same step',
    operationalQuestion: 'Which (sequenceA, sequenceB) commonly fire in the same step?  Hints at compose-eligible workflows.',
    dsl: "SELF JOIN ON (step) GROUP BY (sequenceA, sequenceB) COUNT *",
    run: (rows) => {
      const byStep = groupBy(rows, r => `${r.contractId}::${r.step}`);
      const pairs = new Map();
      for (const [, list] of byStep) {
        const uniq = [...new Set(list.map(r => `${r.machineName}::${r.sequenceId}`))].sort();
        for (let i = 0; i < uniq.length; i++) for (let j = i + 1; j < uniq.length; j++) {
          const k = `${uniq[i]} ↔ ${uniq[j]}`;
          pairs.set(k, (pairs.get(k) ?? 0) + 1);
        }
      }
      return [...pairs.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10).map(([pair, count]) => ({ pair, count }));
    },
  },
  {
    id: 'Q12',
    label: 'most-frequent intermediate vector (single-hop "almost matched")',
    operationalQuestion: 'Which intermediate vectors appear deepest in chains?  These are the workhorse evidence steps.',
    dsl: "UNNEST(provenance) GROUP BY (machine, vector) COUNT *",
    run: (rows) => {
      const g = new Map();
      for (const r of rows) {
        if (!r.provenance) continue;
        // Skip the terminal — we already covered that in Q2.
        for (const v of r.provenance.slice(0, -1)) {
          const k = `${r.machineName}|${v}`;
          g.set(k, (g.get(k) ?? 0) + 1);
        }
      }
      return [...g.entries()].sort((a, b) => b[1] - a[1]).slice(0, 12).map(([k, n]) => {
        const [machine, vector] = k.split('|');
        return { machine, vector, appearancesAsIntermediate: n };
      });
    },
  },
];

// ── Output formatting ───────────────────────────────────────────────────────

function tabulate(rows) {
  if (!Array.isArray(rows)) return JSON.stringify(rows, null, 2);
  if (rows.length === 0) return '(no rows)';
  const cols = Object.keys(rows[0]);
  const widths = cols.map(c => Math.max(c.length, ...rows.map(r => String(r[c] ?? '').length)));
  const sep = widths.map(w => '─'.repeat(w)).join('─┼─');
  const head = cols.map((c, i) => c.padEnd(widths[i])).join(' │ ');
  const body = rows.map(r => cols.map((c, i) => String(r[c] ?? '').padEnd(widths[i])).join(' │ ')).join('\n');
  return `${head}\n${sep}\n${body}`;
}

function describe(q) {
  return `${q.id.padEnd(4)} ${q.label}\n     ❯ ${q.operationalQuestion}\n     DSL: ${q.dsl}`;
}

// ── CLI ─────────────────────────────────────────────────────────────────────

function parseArgs(argv) {
  const args = { list: false, all: false, query: null, json: false, trace: null, machinesDir: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--list') args.list = true;
    else if (a === '--all') args.all = true;
    else if (a === '--query') args.query = argv[++i];
    else if (a === '--json') args.json = true;
    else if (a === '--trace') args.trace = path.resolve(argv[++i]);
    else if (a === '--machines-dir') args.machinesDir = path.resolve(argv[++i]);
    else if (a === '-h' || a === '--help') { printHelp(); process.exit(0); }
    else { console.error(`unknown argument: ${a}`); process.exit(2); }
  }
  args.trace       ??= path.join(ROOT, 'examples', 'contracts.json');
  args.machinesDir ??= path.join(ROOT, 'examples', 'machines');
  return args;
}

function printHelp() {
  console.log('Usage: ces-query [--list | --all | --query Q1] [--json] [--trace PATH] [--machines-dir DIR]');
  console.log('');
  console.log('Canned queries:');
  for (const q of QUERIES) console.log('  ' + describe(q));
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.list) { printHelp(); return; }

  const trace = flattenContracts(args.trace, args.machinesDir);
  console.log(`# trace rows: ${trace.rows.length}  (from ${path.relative(ROOT, args.trace)})\n`);

  const run = (q) => {
    const result = q.run(trace.rows, trace);
    if (args.json) { console.log(JSON.stringify({ id: q.id, label: q.label, dsl: q.dsl, result }, null, 2)); return; }
    console.log(`══ ${q.id}: ${q.label} ══════════════════════════════════════════════`);
    console.log(`❯ ${q.operationalQuestion}`);
    console.log(`DSL: ${q.dsl}`);
    console.log('');
    console.log(tabulate(result));
    console.log('');
  };

  if (args.all) { for (const q of QUERIES) run(q); return; }
  if (args.query) {
    const q = QUERIES.find(x => x.id === args.query);
    if (!q) { console.error(`unknown query: ${args.query}`); process.exit(2); }
    run(q);
    return;
  }
  printHelp();
}

main();
