#!/bin/bash
# Generate nginx upstream blocks from the instance registry and reload nginx.
#
# Reads /tmp/re-registry.json (or $RE_REGISTRY_FILE) and writes
# nginx/conf.d/multi-engine-upstreams.conf.  If nginx is running in the
# Docker stack it is reloaded via `nginx -s reload` (zero-downtime).
#
# Safe to call when no instances are registered — writes an empty conf.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CI_DIR="$SCRIPT_DIR/.."
REGISTRY="${RE_REGISTRY_FILE:-/tmp/re-registry.json}"
CONF_DIR="$CI_DIR/nginx/conf.d"
OUTFILE="$CONF_DIR/multi-engine-upstreams.conf"

mkdir -p "$CONF_DIR"

if [ ! -f "$REGISTRY" ]; then
    printf '# No registry found — no multi-engine upstreams\n' > "$OUTFILE"
    exit 0
fi

python3 - "$REGISTRY" "$OUTFILE" <<'EOF'
import json, sys

reg_path, out_path = sys.argv[1:]
with open(reg_path) as f:
    reg = json.load(f)

instances = reg.get('instances', [])
lines = [
    '# Auto-generated by gen-nginx-upstreams.sh — do not edit by hand',
    '',
]
for inst in instances:
    iid   = inst['id']
    re_hp = inst['re_url'].split('://', 1)[-1]
    pe_hp = inst['pe_url'].split('://', 1)[-1]
    lines.append(f'upstream re_{iid} {{ server {re_hp}; }}')
    lines.append(f'upstream pe_{iid} {{ server {pe_hp}; }}')

with open(out_path, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"Wrote {len(instances)} upstream pair(s) to {out_path}")
EOF

# Reload nginx if it's running in the Docker stack (zero-downtime)
_nginx_ctr=$(docker ps --format '{{.Names}}' 2>/dev/null \
    | grep -E 'reality-engine-tls-proxy|nginx' | head -1 || true)
if [ -n "$_nginx_ctr" ]; then
    docker exec "$_nginx_ctr" nginx -s reload 2>/dev/null && \
        echo "nginx reloaded (zero-downtime)" || \
        echo "nginx reload: container found but reload failed (continuing)"
fi
